# Generated by Django 3.2.5 on 2021-07-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreyApellido', models.CharField(max_length=30)),
                ('DNI', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreyApellido', models.CharField(max_length=30)),
                ('DNI', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=20)),
            ],
        ),
    ]
