# Generated by Django 3.2.5 on 2021-07-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_clientes_tecnicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('finalizado', 'finalizado')], max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.clientes')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.servicios')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.tecnicos')),
            ],
        ),
    ]
