# Generated by Django 3.2.5 on 2021-08-05 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0006_alter_interesados_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesados',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
